ci: kafka 설정 주석처리

diff --git a/.github/workflows/build-and-test-ci.yml b/.github/workflows/build-and-test-ci.yml
--- a/.github/workflows/build-and-test-ci.yml
+++ b/.github/workflows/build-and-test-ci.yml
@@ -20,62 +20,62 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    env:
-      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
+#    env:
+#      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
 
-    services:
-      zookeeper:
-        image: confluentinc/cp-zookeeper
-        ports:
-          - 2181:2181
-        env:
-          ZOOKEEPER_CLIENT_PORT: "2181"
-        options: >-
-          --health-cmd "echo ruok | nc zookeeper 2181 || exit 1"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-          
-      kafka:
-        image: confluentinc/cp-kafka
-        ports:
-          - 9092:9092
-        env:
-          KAFKA_BROKER_ID: 1
-          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
-          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
-          KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
-          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
-        options: >-
-          --health-cmd "kafka-topics --list --bootstrap-server localhost:9092 || exit 1"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+#    services:
+#      zookeeper:
+#        image: confluentinc/cp-zookeeper
+#        ports:
+#          - 2181:2181
+#        env:
+#          ZOOKEEPER_CLIENT_PORT: "2181"
+#        options: >-
+#          --health-cmd "echo ruok | nc zookeeper 2181 || exit 1"
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
+#
+#      kafka:
+#        image: confluentinc/cp-kafka
+#        ports:
+#          - 9092:9092
+#        env:
+#          KAFKA_BROKER_ID: 1
+#          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
+#          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
+#          KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
+#          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+#        options: >-
+#          --health-cmd "kafka-topics --list --bootstrap-server localhost:9092 || exit 1"
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
 
     steps:
-      - name: Wait for Zookeeper to be ready
-        run: |
-          echo "Waiting for Zookeeper..."
-          for i in {1..10}; do
-            if echo ruok | nc localhost 2181 | grep imok; then
-              echo "Zookeeper is up!"
-              break
-            fi
-            echo "Waiting for Zookeeper..."
-            sleep 5
-          done
-
-      - name: Wait for Kafka to be ready
-        run: |
-          echo "Waiting for Kafka..."
-          for i in {1..10}; do
-            if kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1; then
-              echo "Kafka is up!"
-              break
-            fi
-            echo "Waiting for Kafka..."
-            sleep 5
-          done
+#      - name: Wait for Zookeeper to be ready
+#        run: |
+#          echo "Waiting for Zookeeper..."
+#          for i in {1..10}; do
+#            if echo ruok | nc localhost 2181 | grep imok; then
+#              echo "Zookeeper is up!"
+#              break
+#            fi
+#            echo "Waiting for Zookeeper..."
+#            sleep 5
+#          done
+#
+#      - name: Wait for Kafka to be ready
+#        run: |
+#          echo "Waiting for Kafka..."
+#          for i in {1..10}; do
+#            if kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1; then
+#              echo "Kafka is up!"
+#              break
+#            fi
+#            echo "Waiting for Kafka..."
+#            sleep 5
+#          done
 
       - name: Check out repository
         uses: actions/checkout@v4
